server:
  port: 7501
  tomcat:
    max-threads: 10   #Spring boot自带的tomcat线程数默认值为200个
    min-spare-threads: 5    #初始化线程数

spring:
   profiles:
     active: ${profileActive}
   application:
     name: webuy-admin
   security:
     user:
       name: admin
       password: ak402507979


   boot:
     admin:
       monitor:
         period: 10000 #监控刷新时间
       discovery:
         enabled: true  #是否开启自动发现服务


logging:
  config: classpath:config/logback/logback-spring.xml

# 2.0开始，actuator默认不开放，所以要设置为开放
management:
  endpoints:
    web:
      exposure:
        include: "*"  #选择暴露的端点  info,health,env,beans
        #不暴露的端点
        #exclude=env
  endpoint:
    health:
      show-details: ALWAYS   #health endpoint是否必须显示全部细节。默认情况下, /actuator/health 是公开的，并且不显示细节。



---
spring:
  profiles: dev
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:ak402507979@47.99.129.104:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
    ip-address: 127.0.0.01   #server和client不在同一网段使用ip-address:配置
    health-check-url-path: /actuator/health
    status-page-url: http://${eureka.instance.ip-address}:${server.port}/actuator/info
    home-page-url: http://${eureka.instance.ip-address}:${server.port}/
    metadata-map:
      context-path: /actuator
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
      "user.name": ${spring.security.user.name}         #These two are needed so that the server
      "user.password": ${spring.security.user.password}  #can access the protected client endpoints

---
spring:
  profiles: test
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:ak402507979@47.99.129.104:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 30 #续约更新时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 90  #续约到期时间（默认90秒）
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
    ip-address: 106.12.95.245   #server和client不在同一网段使用ip-address:配置
    health-check-url-path: /actuator/health
    status-page-url: http://${eureka.instance.ip-address}:${server.port}/actuator/info
    home-page-url: http://${eureka.instance.ip-address}:${server.port}/
    metadata-map:
      context-path: /actuator
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
      "user.name": ${spring.security.user.name}         #These two are needed so that the server
      "user.password": ${spring.security.user.password}  #can access the protected client endpoints
---