spring:
   application:
     name: webuy-task
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
     driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
     url: jdbc:mysql://47.99.129.104:3306/xxl-job?useUnicode=true&characterEncoding=UTF-8             # 数据库名称
     username: user01
     password: ak402507979
     initialSize: 5
     minIdle: 5
     maxActive: 20
     maxWait: 60000
     poolPreparedStatements: true           # 打开PSCache，并且指定每个连接上PSCache的大小
     maxPoolPreparedStatementPerConnectionSize: 20
     filters: stat,wall,logback    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
     connectionProperties:
        druid:
          stat:
            mergeSql: true   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            slowSqlMillis: 5000
   freemarker:
     allow-request-override: false
     cache: false
     charset: utf-8
     content-type: text/html;charset=utf-8
     suffix: .ftl
     prefix: /job
     request-context-attribute: request
     exposeRequestAttributes: true
     exposeSpringMacroHelpers: true
     exposeSessionAttributes: true
   boot:
      admin:
        auto-registration: true  #客户端是否自动注册
        client:
          enabled: true
          service-url: "http://47.99.129.104:7501"
          username: admin
          password: ak402507979
          instance:
            prefer-ip: true  #客户端是否提供本机真实ip

   security:
     user:
       name: admin
       password: ak402507979

server:
  port: 9301

##配置日志
                #logging:
                #  #配置日志文件路径
                #  file: log
                #  level:
                #    root: debug


logging:
  config: classpath:config/logback/logback-spring.xml

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:ak402507979@47.99.129.104:7001/eureka
    instance:
        instance-id: webuy-task
        prefer-ip-address: true     #访问路径可以显示IP地址

mybatis:
  config-location: classpath:config/mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.weweibuy.po    # 所有Entity别名类所在包
  mapper-locations: classpath:config/mybatis/mapper/**/*.xml                       # mapper映射文件


feign:
  hystrix:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS