spring:
  application:
    name: webuy-eureka
  security:
    user:
      name: admin
      password: ak402507979
  boot:
    admin:
      auto-registration: true  #客户端是否自动注册
      client:
        url: 119.3.11.116:7501
        enabled: true
        username: admin
        password: ak402507979
        instance:
          prefer-ip: true  #客户端是否提供本机真实ip
          service-url: http://${eureka.instance.ip-address}:${server.port}


server:
  port: 7001
  tomcat:
    max-threads: 10   #Spring boot自带的tomcat线程数默认值为200个
    min-spare-threads: 5    #初始化线程数

#配置日志
logging:
  config: classpath:config/logback/logback-spring.xml


eureka:
  instance:
    instance-id: webuy-eureka:${eureka.instance.ip-address}:${server.port}
    hostname: localhost #eureka服务端的实例名称
    ip-address: 47.99.129.104
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #  是否从eureka上获取注册信息   false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://admin:ak402507979@47.99.129.104:7001/eureka
       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

